# Generated by Django 5.1.6 on 2025-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_time_of_addtion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
