# Generated by Django 5.1.6 on 2025-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cartitem_price_at_time_of_addtion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_time_of_addtion',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_at_time_of_addition',
            field=models.FloatField(default=0.0),
        ),
    ]
